### ISSUE TITLE
How do I use my own conf file inside Openshift?

### ISSUE THREAD

**Issue by SimonVuong** [sclorg/mongodb-container#213]
I see that the readme says to...

For example to use configuration file stored in /home/user directory use this option for docker run command: -v /home/user/mongod.conf:/etc/mongod.conf:Z.

But how do we edit the docker run command inside Openshift?

**Comment by bparees** [comment]
if you're using the image in openshift you should be using volumes(or configmaps or secrets) to mount content into the running container.

**Comment by SimonVuong** [comment]
So how do we move the file from volume to the target location without editing the dockerfile or the scripts?

**Comment by bparees** [comment]
you don't move it, you specify the mount path to put the file in the approach location within the container.

**Comment by SimonVuong** [comment]
could you go into more detail on how to do this please?

i found my deployment config and have this 
```
          volumeMounts:
            -
              name: data
              mountPath: /var/lib/mongodb/data
```
