### ISSUE TITLE
erroneous error message when specifying admin password and a database name

### ISSUE THREAD

**Issue by elmiko** [sclorg/mongodb-container#235]
while testing out this image i am running into a problem where the error output from the container does not match the behavior i am seeing.

## steps to reproduce:

1. create a new container with the following command

```
oc new-app centos/mongodb-32-centos7 \
-e MONGODB_ADMIN_PASSWORD=admin \
-e MONGODB_DATABASE=foo \
--name mongodb
```

this results in a pod that will fail with the following error log:

```
You must specify the following environment variables:
  MONGODB_ADMIN_PASSWORD
Optionally you can provide settings for user with 'readWrite' role:
  MONGODB_USER
  MONGODB_PASSWORD
  MONGODB_DATABASE
MongoDB settings:
  MONGODB_QUIET (default: true)
```

i am positive that the environment variable is set, but i am informed that the true error is that you cannot specify the admin password **and** a database name.

this is the result of running the new-app command with the `-o yaml` option:

```
apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mongodb
    name: mongodb
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: centos/mongodb-32-centos7
      from:
        kind: DockerImage
        name: centos/mongodb-32-centos7
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mongodb
    name: mongodb
  spec:
    replicas: 1
    selector:
      app: mongodb
      deploymentconfig: mongodb
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: mongodb
          deploymentconfig: mongodb
      spec:
        containers:
        - env:
          - name: MONGODB_ADMIN_PASSWORD
            value: admin
          - name: MONGODB_DATABASE
            value: ophicleide
          image: centos/mongodb-32-centos7
          name: mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/mongodb/data
            name: mongodb-volume-1
        volumes:
        - emptyDir: {}
          name: mongodb-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mongodb
        from:
          kind: ImageStreamTag
          name: mongodb:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mongodb
    name: mongodb
  spec:
    ports:
    - name: 27017-tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app: mongodb
      deploymentconfig: mongodb
  status:
    loadBalancer: {}
kind: List
metadata: {}
```

## suggested solution

the error message should be made more explicit, for example let the user know that they cannot specify both. alternatively, allow the user to specify both.
